name: GitHub Pages
on:
  push:
    branches:
      - master  # 根据实际主分支名调整（如main）
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Cache-Control
        run: |
          mkdir -p _site
          # 使用rsync复制文件，自动排除_site目录，支持隐藏文件
          rsync -av --exclude='_site/' . _site/
          echo -e "/*\n  Cache-Control: public, max-age=31536000" > _site/_headers
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          # 替换为之前添加的GH_PAGES_TOKEN
          github_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: ./_site
    